# **Задание№1**

In [21]:
import numpy as np

# **Задание№2**

In [22]:
# Создание массивов NumPy

In [23]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [24]:
#Матрица
b = np.array([[12, 20, 17], [7, 13, 15]])
b

array([[12, 20, 17],
       [ 7, 13, 15]])

In [25]:
#Матрица нулей
c = np.zeros((5,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#Матрица единиц
d = np.ones((5,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#Единичная матрица (линал)
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
f = np.empty((3, 4))
f

array([[1.22427218e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.58817677e-052, 5.88874464e-091,
        2.80474176e-032],
       [1.26880636e-076, 7.27309754e-043, 6.48224659e+170,
        5.82471487e+257]])

In [29]:
# Баловство с arange
g = np.arange(1,101, 1)
print(g)
print(np.arange(1,20,0.05))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1.    1.05  1.1   1.15  1.2   1.25  1.3   1.35  1.4   1.45  1.5   1.55
  1.6   1.65  1.7   1.75  1.8   1.85  1.9   1.95  2.    2.05  2.1   2.15
  2.2   2.25  2.3   2.35  2.4   2.45  2.5   2.55  2.6   2.65  2.7   2.75
  2.8   2.85  2.9   2.95  3.    3.05  3.1   3.15  3.2   3.25  3.3   3.35
  3.4   3.45  3.5   3.55  3.6   3.65  3.7   3.75  3.8   3.85  3.9   3.95
  4.    4.05  4.1   4.15  4.2   4.25  4.3   4.35  4.4   4.45  4.5   4.55
  4.6   4.65  4.7   4.75  4.8   4.85  4.9   4.95  5.    5.05  5.1   5.15
  5.2   5.25  5.3   5.35  5.4   5.45  5.5   5.55  5.6   5.65  5.7   5.75
  5.8   5

# **Задание№3**

In [30]:
print(e.shape)
type(e)

(3, 3)


numpy.ndarray

# **Задание№4**

In [31]:
h = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(h)

print( h[0])     # Первый элемент
print(h[4])     # Пятый элемент
print(h[-1])   # Последний элемент
#Срезы
print(h[2:5])           
print(h[:4])             
print(h[6:])             
print(h[::2])           
print(h[1::2])         
print(h[::-1])       

[ 10  20  30  40  50  60  70  80  90 100]
10
50
100
[30 40 50]
[10 20 30 40]
[ 70  80  90 100]
[10 30 50 70 90]
[ 20  40  60  80 100]
[100  90  80  70  60  50  40  30  20  10]


# **Задание№5**

In [32]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print("arr1:", arr1)
print("arr2:", arr2)

print("\n--- Векторные операции ---")
print(arr1 + arr2)          # Поэлементное сложение
print(arr2 - arr1)          # Поэлементное вычитание
print(arr1 * arr2)          # Поэлементное умножение
print(arr2 / arr1)          # Поэлементное деление
print(arr1 ** 2)              # Возведение в степень
print(arr1 * 10)              # Умножение на скаляр
print("\n--- Базовые статистические функции ---")
data = np.array([2, 4, 6, 8, 10, 12])
print("data:", data)
print("Среднее значение:", np.mean(data))
print("Сумма:", np.sum(data))
print("min:", np.min(data))
print("max:", np.max(data))
print("Стандартное отклонение", np.std(data))
print("Медиана:", np.median(data))

arr1: [1 2 3 4 5]
arr2: [10 20 30 40 50]

--- Векторные операции ---
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[10 20 30 40 50]

--- Базовые статистические функции ---
data: [ 2  4  6  8 10 12]
Среднее значение: 7.0
Сумма: 42
min: 2
max: 12
Стандартное отклонение 3.415650255319866
Медиана: 7.0
